version: 0.2

phases:
  build:
    commands:
      - chmod +x ./AWSLCAndroidTestRunner/gradlew
      - cd AWSLCAndroidTestRunner
      - ./gradlew assembleDebug
      - ./gradlew assembleAndroidTest
      - ls app/build/outputs/apk
artifacts:
  files:
     - './AWSLCAndroidTestRunner/app/build/outputs/**/*.apk'
     - './AWSLCAndroidTestRunner/app/build/outputs/androidTest/**/*.apk'
  discard-paths: yes

