version: 0.2

phases:
  build:
    commands:
      - chmod +x ./AWSLCAndroidTestRunner/gradlew
      - cd AWSLCAndroidTestRunner
      - ./gradlew assembleDebug
artifacts:
  files:
     - './AWSLCAndroidTestRunner/app/build/outputs/**/*.apk'
     - './AWSLCAndroidTestRunner/app/build/outputs/**/**/*.apk'
  discard-paths: yes

