version: 0.2

phases:
  build:
    commands:
      - chmod +x ./AWSLCAndroidTestRunner/gradlew
      - cd AWSLCAndroidTestRunner
      - ./gradlew assembleDebug
      - ./gradlew assembleAndroidTest
      - ls app/build/outputs/apk
      - mv app/build/outputs/apk app/build/outputs/non-fips
      - ./gradlew clean
      - ./gradlew assembleDebug -PFIPS
      - ./gradlew assembleAndroidTest -PFIPS
      - mv app/build/outputs/apk app/build/outputs/fips
artifacts:
  files:
     - './AWSLCAndroidTestRunner/app/build/outputs/**/*.apk'
  discard-paths: yes

