version: 0.2

phases:
  build:
    commands:
      - chmod +x ./AWSLCAndroidTestRunner/gradlew
      - cd AWSLCAndroidTestRunner
      - ./gradlew assembleDebug
      - ./gradlew assembleAndroidTest
      - mv app/build/outputs/apk apk-artifacts/non-fips
      - ls apk-artifacts
      - ls apk-artifacts/non-fips
      - ./gradlew clean
      - ./gradlew assembleDebug -PFIPS
      - ./gradlew assembleAndroidTest -PFIPS
      - mv app/build/outputs/apk apk-artifacts/fips
      - ls apk-artifacts
      - ls apk-artifacts/fips
      - ls apk-artifacts/fips/androidTest
artifacts:
  files:
     - './AWSLCAndroidTestRunner/apk-artifacts/**/**/*.apk'
  discard-paths: yes

