version: 0.2

phases:
  build:
    commands:
      - chmod +x ./AWSLCAndroidTestRunner/gradlew
      - cd AWSLCAndroidTestRunner
      - mkdir apk-artifacts
      - ./gradlew assembleDebug
      - ./gradlew assembleAndroidTest
      - mv app/build/outputs/apk apk-artifacts/non-fips-dbg
      - ./gradlew clean
      - ./gradlew assembleDebug -PRelease
      - ./gradlew assembleAndroidTest -PRelease
      - mv app/build/outputs/apk apk-artifacts/non-fips-rel
      - ./gradlew clean
      - ./gradlew assembleDebug -PFIPS
      - ./gradlew assembleAndroidTest -PFIPS
      - mv app/build/outputs/apk apk-artifacts/fips
      - ls apk-artifacts
artifacts:
  files:
     - './AWSLCAndroidTestRunner/apk-artifacts/**/**/*.apk'
  discard-paths: yes

