[package]
name = "aws-lc-sys"
version = "__AWS_LC_SYS_VERSION__"
authors = ["AWS-LC"]
edition = "2021"

[build-dependencies]
cmake = "0.1.48"

[dependencies]
libc = "0.2"

[dev-dependencies]
sha1 = "0.10.1"

