name: AWS-LC ABI Diff
on:
  pull_request:
    branches: [ '*' ]
env:
  DOCKER_BUILDKIT: 1
  GOPROXY: https://proxy.golang.org,direct
jobs:
  crypto:
    name: libcrypto
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: aws/aws-lc
          ref: ${{ github.ref }}
          path: ${{ github.workspace }}/next
      - uses: actions/checkout@v3
        with:
          repository: aws/aws-lc
          ref: ${{ github.base.ref }}
          path: ${{ github.workspace }}/previous
      - name: Build Docker Image
        working-directory: ${{ github.workspace }}/next/.github/docker_images/abidiff
        run: |
          docker build -t abidiff .
      - name: Perform ABI Diff
        run: |
          docker run -v ${{ github.workspace }}/previous:/previous -v ${{ github.workspace }}/next:/next -- abidiff crypto
  ssl:
    name: libssl
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: aws/aws-lc
          ref: ${{ github.ref }}
          path: ${{ github.workspace }}/next
      - uses: actions/checkout@v3
        with:
          repository: aws/aws-lc
          ref: ${{ github.base.ref }}
          path: ${{ github.workspace }}/previous
      - name: Build Docker Image
        working-directory: ${{ github.workspace }}/next/.github/docker_images/abidiff
        run: |
          docker build -t abidiff .
      - name: Perform ABI Diff
        run: |
          docker run -v ${{ github.workspace }}/previous:/previous -v ${{ github.workspace }}/next:/next -- abidiff ssl
