name: Miscellaneous test jobs
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true
jobs:
  pre-sandbox:
    if: github.repository_owner == 'aws'
    runs-on: ubuntu-latest
    steps:
      - name: Install OS Dependencies
        run: |
          sudo apt-get update -o Acquire::Languages=none -o Acquire::Translation=none
          sudo apt-get -y --no-install-recommends install \
            cmake clang ninja-build golang
          echo "CC=clang" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV
      - name: Install seccomp dependencies
        run: |
          sudo apt-get -y --no-install-recommends install libseccomp-dev
      - uses: actions/checkout@v3
      - name: Test sandbox configuration
        run: |
          ./tests/ci/run_presandbox_tests.sh

  assert-license-statement-in-pr-description:
    if: github.repository_owner == 'aws'
    runs-on: ubuntu-latest

    steps:
    - name: Install jq
      run: |
        sudo apt-get update -o Acquire::Languages=none -o Acquire::Translation=none
        sudo apt-get install -y jq

    - name: Check PR description
      run: |
        # Fetches the PR description.
        PR_DESCRIPTION=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} | jq -r .body)

        LICENSE_STATEMENT="By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and the ISC license."

        echo "PR description: ${PR_DESCRIPTION}"
        echo "Must contain: ${LICENSE_STATEMENT}"

        # Assert this is the case.
        if echo "${PR_DESCRIPTION}" | grep -xq "${LICENSE_STATEMENT}"; then
          echo "PR description contains license statement."
        else
          echo "Error: PR description does not contain the required license statement."
          exit 1
        fi
