name: macOS CI

# Workflow syntax.
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
on:
  pull_request:
    branches:
      - '*'

env:
  PACKAGE_NAME: aws-lc
  # Used to enable ASAN test dimension.
  AWSLC_NO_ASM_FIPS: 1

jobs:
  macOS:
    runs-on: macos-11 # latest
    steps:
    - uses: actions/checkout@v2
    - name: Build ${{ env.PACKAGE_NAME }}
      run: |
        ./tests/ci/run_posix_tests.sh

  macOS-FIPS:
    runs-on: macos-11 # latest
    steps:
    - uses: actions/checkout@v2
    - name: Build ${{ env.PACKAGE_NAME }} with FIPS mode
      run: |
        echo "Do nothing"
# fips-2021-10-20 does not support FIPS on macOS.
# TODO(CryptoAlg-1286): enable below FIPS cript when related source code are copied to FIPS branch.
        # ./tests/ci/run_fips_tests.sh
